#!/usr/bin/env node
require('clear')();
var config = require('./server/config');

//mongoose setup
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect(config.db.url);

var artistsIds = [];
var albumIds = [];
var trackIds = [];
var categoryIds = [];

var _  = require('lodash');
var argv = require('minimist')(process.argv.slice(2));


// require("./cli/category")(function(a){
//   categoryIds = a;
//   require("./cli/chart")(categoryIds, function(a){
//
//     console.log('done');
//     process.exit(0);
//   });
// });

//basics
require("./cli/category")(function(a){
  categoryIds = a;
  require("./cli/artist")(artistsIds, function(a){
    artistsIds = a;
    require("./cli/relatedartist")(artistsIds, function(a){
      require("./cli/track")(function(a){
        trackIds = a;
        require("./cli/album")(artistsIds, trackIds, function(a){
          albumIds = a;
          require("./cli/chart")(categoryIds, function(a){

            console.log('done!');
            process.exit(1);
          });

        });
      });
    });
  });
});
