#!/usr/bin/env node
require('clear')();
var config = require('./server/config');

//mongoose setup
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect(config.db.url);

var artistsIds = [];

var _  = require('lodash');
var argv = require('minimist')(process.argv.slice(2));

var t = argv["t"];
if(!t){
  console.log(chalk.red("No type given"));
  process.exit(1);
}


require("./cli/relatedartist")(artistsIds, function(a){
  process.exit(1);

});


// require("./cli/artist")(artistsIds, function(a){
//   artistsIds = a;
//   process.exit(1);
// });
